### ISSUE TITLE
Software Error

### ISSUE THREAD

**Issue by beardedsailor** [sanjayvsingh/weather#6]
I tried https://sanvash.com/cgi-bin/weather.pl?loc=sydney on your weather app
but I got this error. kindly resolve the bug

Software error:
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "Can't connect to ope...") at weather.pl line 312, <DATA> line 3.

**Comment by sanjayvsingh** [comment]
Added some hardening code around this so a location request doesn't bring down the whole site. Looks like the Mapquest API is blocking requests from my ISP now. Looking into it.

**Comment by sanjayvsingh** [comment]
Looks like the block was lifted and this is working again. There is now better error detection and reporting when the geocoding API is not available so it doesn't bring down the whole site.
